In [1]:
import numpy as np
def softmax(x):
  exp_x = np.exp(x - np.max(x,axis=1,keepdims=True))
  return exp_x/np.sum(exp_x,axis=1,keepdims=True)
n = np.array([3.15,5.3,-2.1]).reshape(1,3)
n


array([[ 3.15,  5.3 , -2.1 ]])

In [4]:

type(n)


numpy.ndarray

In [5]:
m = softmax(n)
m


array([[1.04274135e-01, 8.95178684e-01, 5.47180443e-04]])

In [6]:
class CrossEntropy:
  def forward(self,X,y): #Feed Forward NN or Backpropagation
    y_idx = y.argmax()
    self.p = softmax(X)
    cross_entropy = -np.log(self.p[y_idx])
    loss = cross_entropy
    return loss
  def backward(self,X,y):
    y_idx = y.argmax()
    grad = softmax(X)
    grad[y_idx] = grad[y_idx]-1
    return grad


In [7]:
n1 = np.array([3.15,5.3,-2.1]).reshape(1,3)
n1


array([[ 3.15,  5.3 , -2.1 ]])

In [8]:
n2 = np.array([1,0,0]).reshape(1,3)
n2


array([[1, 0, 0]])

In [9]:
#Object of the class
ce = CrossEntropy()
ce.forward(n1,n2)


array([2.26073193, 0.11073193, 7.51073193])

In [10]:
ce.backward(n1,n2)

array([[-0.89572586, -0.10482132, -0.99945282]])